name: Deployment Expanded
on:  
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - modules/**
jobs:
  delta:
    runs-on: ubuntu-latest
    steps:
      - name: Get code for delta client
        uses: actions/checkout@v3
        with:
          repository: WolfgangBaeck/REB3AZURE
          path: ./r3dev-delta
      - name: Show Files
        run: ls -l -R
      # Install the preferred version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          cd r3dev-delta
          terraform init 

      # Run a terraform plan 
      - name: Terraform Plan
        id: plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: terraform plan -no-color
        
        # On push to main, build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: terraform apply -auto-approve

  epsilon:
    runs-on: ubuntu-latest
    steps:
      - name: Get code for epsilon client
        uses: actions/checkout@v3
        with:
          repository: WolfgangBaeck/REB3AZURE
          path: ./r3dev-epsilon
      - name: Output contents on runner
        run: ls -l -R
  zeta:
    runs-on: ubuntu-latest
    steps:
      - name: Get code for zeta client
        uses: actions/checkout@v3
        with:
          repository: WolfgangBaeck/REB3AZURE
          path: ./r3dev-zeta
      - name: Output contents on runner
        run: ls