name: Deployment
on:
  workflow_dispatch:

jobs:
  delta:
    runs-on: ubuntu-latest
    steps:
    # Checkout client files first to runner's root file system
      - name: Get code for delta client
        uses: actions/checkout@v3
        with:
          repository: WolfgangBaeck/REB3Delta

    # Checkout the module repository into separate folder protecting root files
      - name: Checkout Modules
        uses: actions/checkout@v3
        with:
          path: modules

      - name: Output filesystem
        run: ls -R

      - name: Run Terraform Action
        uses: ./.github/actions/terraform

  epsilon:
    runs-on: ubuntu-latest
    steps:
      - name: Get code for epsilon client
        run: echo "Running for epsilon"

  zeta:
    runs-on: ubuntu-latest
    steps:
      - name: Get code for zeta client
        run: echo "Running for zeta"